spring:
  application:
    name: mianbao-agent
  profiles:
    active: local
  ai:
    dashscope:
      api-key: ${ai.api-key}
      chat:
        options:
          model: qwen3-max-2025-09-23
    mcp:
      client:
        stdio:
          servers-configuration: classpath:mcp-servers.json

  datasource:
    url: jdbc:mysql://localhost:3306/ai_agent_db?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8123
  servlet:
    context-path: /api

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.zhishi.aiagent.controller

mybatis:

  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zhishi.aiagent.dto
  configuration:
    map-underscore-to-camel-case: true

knife4j:
  enable: true
  setting:
    language: zh_cn

map:
  api-key: ${amap.api-key}
  js-key: ${amap.js-key}
  security-js-code: ${amap.security-js-code}
